# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['perf_doctor.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config.py', '.'),
        ('templates', 'templates'),
        ('modules', 'modules'),
        ('core', 'core'),
    ],
    hiddenimports=[
        'websockets',
        'psutil',
        'requests',
        'jinja2',
        'modules.report_generator',
        'modules.performance_doctor',
        'modules.chrome_manager',
        'modules.devtools_client',
        'modules.network_report_generator',
        'modules.performance_collector',
        'modules.collectors.base_collector',
        'modules.collectors.collector_manager',
        'modules.collectors.memory_collector',
        'modules.collectors.navigation_collector',
        'modules.collectors.network_collector',
        'modules.collectors.paint_collector',
        'modules.collectors.performance_metrics_collector',
        'core.main',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='perf-doctor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
